### ISSUE TITLE
sysconfig documentation has a typo

### ISSUE THREAD

**Issue by wfsaxton** [kschu91/puppet-gogs#5]
USER should be GOGS_USER

    class { '::gogs':
        sysconfig => {
            'NAME' => { value => 'gogitsgogs' },
            'USER' => { value => 'johndoe' },
        }
    }

**Comment by kschu91** [comment]
Hi wfsaxton,

the sysconfig parameters depend on the distribution you are running.
For Ubuntu/Debian it is called `USER` and for CentOS/RedHat `GOGS_USER`.

This is because the gogs provided init scripts have different namings for different distributions.
See [here for CentOS/RedHat](https://github.com/gogits/gogs/blob/master/scripts/init/centos/gogs) and [here for Ubuntu/Debian](https://github.com/gogits/gogs/blob/master/scripts/init/debian/gogs).

I will specify the documentation on that.

**Comment by kschu91** [comment]
Maybe it is the `LOGPATH` if you are using CentOS?

**Comment by kschu91** [comment]
[README](https://github.com/kschu91/puppet-gogs/blob/master/README.md#sysconfig) is updated regarding this.
