### ISSUE TITLE
gogs service restart is triggered on each puppet run

### ISSUE THREAD

**Issue by kschu91** [kschu91/puppet-gogs#9]
The "download_gogs_from_github" exec should have a "unless" that checks the version like [here](https://github.com/Jana-Mobile/puppet-gogs/commit/dbbda9b647e76bff73eeb1e375805ec53b0def77).

**Comment by SeanHood** [comment]
Is this due to the file being rewritten by puppet and by gogs? I have modified app_ini.pp to use puppetlabs-inifile to make changes to this file. The way in which I've changed this would break compatibility with the configuration, however this could be easily changed. Would you be interested in a PR?

It's not PR ready yet, however here is the commit: https://github.com/SeanHood/puppet-gogs/commit/ea7888de95209540f8def8b957c4038d3ac058ff

**Comment by kschu91** [comment]
Hi. Sorry for the very late response. The issue is related to the "download_gogs_from_github" exec which should have a "unless" that checks the version like [here](https://github.com/Jana-Mobile/puppet-gogs/commit/dbbda9b647e76bff73eeb1e375805ec53b0def77). However, happy to accept a pull request when the old configuration could still be supported.

**Comment by kschu91** [comment]
fixed with version 1.3.0.
